from huobi.model import *


class AccountEvent:
    """
    The account change information received by subscription of account.

    :member
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        change_type: The event that asset change notification related.
        account_change_list: The list of account change, the content is AccountChange class

    """

    def __init__(self):
        self.timestamp = 0
        self.change_type = AccountChangeType.INVALID
        self.account_change_list = list()
