
from huobi.impl.utils.timeservice import convert_cst_in_millisecond_to_utc
from huobi.model import *


class OrderDetailRequest:
    """
    The order update received by subscription of order update.

    :member
        symbol: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        data: The order detail.

    """

    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.topic = ""
        self.client_req_id = ""
        self.data = Order()

    @staticmethod
    def json_parse(json_data, account_id_type_map):
        req_obj = OrderDetailRequest()
        req_obj.timestamp = convert_cst_in_millisecond_to_utc(json_data.get_int("ts"))
        req_obj.client_req_id = json_data.get_string("cid")
        req_obj.topic = json_data.get_string("topic")
        order_json = json_data.get_object("data")

        account_id = order_json.get_int("account-id")
        account_type = AccountType.INVALID
        if account_id in account_id_type_map:
            account_type = account_id_type_map[account_id]

        order_obj = Order.json_parse(order_json, account_type)
        req_obj.symbol = order_obj.symbol
        req_obj.data = order_obj

        return req_obj

    def print_object(self, format_data=""):
        from huobi.base.printobject import PrintBasic
        PrintBasic.print_basic(self.symbol, "Symbol")
        PrintBasic.print_basic(self.timestamp, "Timestamp")
        PrintBasic.print_basic(self.client_req_id, "Client Req ID")
        PrintBasic.print_basic(self.topic, "Topic")
        print("order detail as below :")
        self.data.print_object()


if __name__ == "__main__":
    from huobi.impl.utils import parse_json_from_string
    json_str = """{"op":"req","ts":1569314632371,"topic":"orders.detail","err-code":0,"cid":"1569314632312","data":{"id":48902976275,"symbol":"eosusdt","account-id":10057288,"amount":"10.000000000000000000","price":"0.0","created-at":1569033319999,"type":"sell-market","finished-at":1569033320090,"source":"spot-app","state":"filled","canceled-at":0,"filled-amount":"10.000000000000000000","filled-cash-amount":"40.583000000000000000","filled-fees":"0.081166000000000000"}}"""
    json_bytes = bytes(json_str, encoding='utf8')
    json_wrapper = parse_json_from_string(json_bytes.decode("utf-8"))

    order_req_obj = OrderDetailRequest.json_parse(json_wrapper)

    from huobi.base.printobject import PrintBasic, PrintMix
    print("---- order list:  ----")
    PrintBasic.print_basic(order_req_obj.symbol, "Symbol")
    PrintBasic.print_basic(order_req_obj.timestamp, "Timestamp")
    PrintBasic.print_basic(order_req_obj.client_req_id, "Client Req ID")
    PrintBasic.print_basic(order_req_obj.topic, "Topic")
    print("order detail as below :")
    order = order_req_obj.data
    PrintMix.print_data(order)
    print()