from huobi.model import *
from huobi.model.orderupdatenew import OrderUpdateNew


class OrderUpdateNewEvent:
    """
    The order update received by subscription of order update.

    :member
        symbol: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        data: The order detail.

    """

    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.data = OrderUpdateNew()
