from huobi.model import *


class PingPongEvent:
    """
    The pingpong information received by subscription of pingpong.

    :member
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        op: The operate.
    """

    def __init__(self):
        self.timestamp = 0
        self.op = OperateMode.INVALID
