from huobi.model.tradestatistics import TradeStatistics


class TradeStatisticsEvent:
    """
    The 24H trade statistics received by subscription of trade statistics.

    :member
        symbol: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        trade_statistics: The trade statistics.
    """
    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.trade_statistics = TradeStatistics()
