
class AccountBalanceReq:
    """
    The account change information received by subscription of account.

    :member
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        change_type: The event that asset change notification related.
        account_list: The list of account and balance

    """

    def __init__(self):
        self.timestamp = 0
        self.client_req_id = ""
        self.topic = ""
        self.account_list = list()


    def print_object(self, format_data=""):
        from huobi.utils.print_mix_object import PrintBasic
        PrintBasic.print_basic(self.timestamp, format_data + "Timestamp")
        PrintBasic.print_basic(self.client_req_id, format_data + "Client Order ID")
        PrintBasic.print_basic(self.topic, format_data + "Topic")
        print()
        if len(self.account_list):
            for row in self.account_list:
                row.print_object()
                print()