from huobi.constant import *


class AccountChangeEvent:
    """
    The account change information received by subscription of account.

    :member
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        change_type: The event that asset change notification related.
        account_change_list: The list of account change, the content is AccountChange class

    """

    def __init__(self):
        self.op = ""
        self.ts = 0
        self.topic = ""
        self.event = ""
        #self.change_type = AccountChangeType.INVALID
        self.account_change_list = list()

    def print_object(self, format_data=""):
        from huobi.utils.print_mix_object import PrintBasic
        PrintBasic.print_basic(self.op, format_data + "Op")
        PrintBasic.print_basic(self.ts, format_data + "Timestamp")
        PrintBasic.print_basic(self.topic, format_data + "Topic")
        PrintBasic.print_basic(self.event, format_data + "Event")
        print()
        if len(self.account_change_list):
            for row in self.account_change_list:
                row.print_object()
                print()