from huobi.model.market import PriceDepth


class PriceDepthReq:
    """
    The price depth received by subscription of price depth.

    :member
        symbol: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        data: The price depth.

    """

    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.ch = ""
        self.id = ""

        self.data = PriceDepth()


    def print_object(self, format_data=""):
        from huobi.utils.printobject import PrintBasic
        PrintBasic.print_basic(self.symbol, format_data + "Symbol")
        PrintBasic.print_basic(self.timestamp, format_data + "Time")
        PrintBasic.print_basic(self.ch, format_data + "Channel")
        PrintBasic.print_basic(self.id, format_data + "ID")
        self.data.print_object(format_data)


