
from huobi.serialize.market.depthentry import DepthEntrySerial
from huobi.serialize.market.last_trade_bestquote import LastTradeAndBestQuoteSerial
from huobi.serialize.market.pricedepth import PriceDepthSerial
from huobi.serialize.market.pricedepth_event import PriceDepthEventSerial
from huobi.serialize.market.pricedepth_req import PriceDepthReqSerial
from huobi.serialize.market.pricedepth_bbo import PriceDepthBboSerial
from huobi.serialize.market.pricedepth_bbo_event import PriceDepthBboEventSerial
from huobi.serialize.market.pricedepth_event import PriceDepthEventSerial
from huobi.serialize.market.pricedepth_req import PriceDepthReqSerial
from huobi.serialize.market.trade_detail import TradeDetailSerial
