from huobi.model.trade import Order


class OrderDetailReq:
    """
    The order update received by subscription of order update.

    :member
        symbol: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        topic : request topic
        client_req_id : client request id
        data: The order detail.

    """

    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.topic = ""
        self.client_req_id = ""
        self.data = Order()


    def print_object(self, format_data=""):
        from huobi.utils.printobject import PrintBasic
        PrintBasic.print_basic(self.symbol, format_data + "Symbol")
        PrintBasic.print_basic(self.timestamp, format_data + "Timestamp")
        PrintBasic.print_basic(self.client_req_id, format_data + "Client Req ID")
        PrintBasic.print_basic(self.topic, format_data + "Topic")
        print("order detail as below :")
        self.data.print_object()