from huobi.model.trade.order_update import OrderUpdate


class OrderUpdateEvent:
    """
    The order update received by subscription of order update.

    :member
        topic: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        data: The order detail.

    """

    def __init__(self):
        self.topic = ""
        self.ts = 0
        self.data = OrderUpdate()

    def print_object(self, format_data=""):
        from huobi.utils.print_mix_object import PrintBasic
        PrintBasic.print_basic(self.topic, format_data + "Topic")
        PrintBasic.print_basic(self.ts, format_data + "Timestamp")

        orderupdate = self.data
        orderupdate.print_object()