
class OrderListReq:
    """
    The order update received by request of order list.

    :member
        symbol: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        topic: request topic
        client_req_id: client request ID
        order_list : order list

    """

    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.client_req_id = ""
        self.topic = ""
        self.order_list = list()


    def print_object(self, format_data=""):
        from huobi.utils.printobject import PrintBasic
        PrintBasic.print_basic(self.symbol, format_data + "Symbol")
        PrintBasic.print_basic(self.timestamp, format_data + "Timestamp")
        PrintBasic.print_basic(self.client_req_id, format_data + "Client Req ID")
        PrintBasic.print_basic(self.topic, format_data + "Topic")
        print("Order List as below : count " + str(len(self.order_list)))
        if len(self.order_list):
            for order_obj in self.order_list:
                order_obj.print_object("\t ")
                print()

