from huobi.model.trade import TradeStatistics


class TradeStatisticsReq:
    """
    The 24H trade statistics received by request of trade statistics only once.

    :member
        symbol: The symbol you subscribed.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        trade_statistics: The trade statistics.
    """
    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.trade_statistics = TradeStatistics()

    def print_object(self, format_data=""):
        from huobi.utils.printobject import PrintBasic
        PrintBasic.print_basic(self.timestamp, format_data + "Timestamp")
        PrintBasic.print_basic(self.symbol, format_data + "Symbol")
        self.trade_statistics.print_object()